# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a12tcpg238-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Vivado_projects/Crystals-kyber/Crystals-kyber.cache/wt [current_project]
set_property parent.project_path E:/Vivado_projects/Crystals-kyber/Crystals-kyber.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Vivado_projects/Crystals-kyber/Crystals-kyber.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/phi.coe
add_files E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/invphi.coe
add_files E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/phi_rev.coe
add_files E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/invphi_rev.coe
add_files E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/pwphi_rev.coe
add_files E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/pwphi.coe
read_verilog -library xil_defaultlib {
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/new/Kyber_Server.v
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/new/butterfly_Client.v
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/new/butterfly_Server.v
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/new/NTT_core_Client.v
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/new/Kyber_Client.v
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/new/NTT_core_Server.v
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/new/reduc.v
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/new/hash_core_Client.v
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/new/hash_core_Server.v
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/new/pattern.v
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/imports/decode_Server.v
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/imports/encode_Server.v
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/imports/decode_Client.v
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/imports/encode_Client.v
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/new/decode_keccak.v
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/new/mux4to2.v
}
read_vhdl -library xil_defaultlib {
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/imports/pi.vhd
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/imports/RegisterFDRE.vhd
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/imports/chi.vhd
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/imports/iota.vhd
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/imports/StateMachine.vhd
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/imports/rho.vhd
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/imports/Keccak1600.vhd
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/imports/theta.vhd
  E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/imports/imports/Round.vhd
}
read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_6_1/fifo_generator_6.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_6_1/fifo_generator_6.xdc]
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_6_1/fifo_generator_6_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_8/fifo_generator_8.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_8/fifo_generator_8.xdc]
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_8/fifo_generator_8_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_7/fifo_generator_7.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_7/fifo_generator_7.xdc]
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_7/fifo_generator_7_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/dist_mem_gen_7/dist_mem_gen_7.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/dist_mem_gen_7/dist_mem_gen_7_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2.xdc]
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_2/fifo_generator_2_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_3/fifo_generator_3.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_3/fifo_generator_3.xdc]
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_3/fifo_generator_3_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_4/fifo_generator_4.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_4/fifo_generator_4.xdc]
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_4/fifo_generator_4_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_5/fifo_generator_5.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_5/fifo_generator_5.xdc]
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_5/fifo_generator_5_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1.xdc]
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_1/fifo_generator_1_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_3/c_shift_ram_3.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_3/c_shift_ram_3_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_6/c_shift_ram_6.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_6/c_shift_ram_6_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_8/c_shift_ram_8.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_8/c_shift_ram_8_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_5/c_shift_ram_5.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_5/c_shift_ram_5_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_11/c_shift_ram_11.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_11/c_shift_ram_11_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_2/c_shift_ram_2.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_2/c_shift_ram_2_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_4/c_shift_ram_4.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_4/c_shift_ram_4_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/dist_mem_gen_5/dist_mem_gen_5.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/dist_mem_gen_5/dist_mem_gen_5_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/dist_mem_gen_6/dist_mem_gen_6.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/dist_mem_gen_6/dist_mem_gen_6_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_9/c_shift_ram_9.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_9/c_shift_ram_9_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_0/c_shift_ram_0_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_1/c_shift_ram_1.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/c_shift_ram_1/c_shift_ram_1_ooc.xdc]

read_ip -quiet E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property used_in_implementation false [get_files -all e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/constrs_1/imports/new/constr.xdc
set_property used_in_implementation false [get_files E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/constrs_1/imports/new/constr.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Kyber_Client -part xc7a12tcpg238-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Kyber_Client.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file Kyber_Client_utilization_synth.rpt -pb Kyber_Client_utilization_synth.pb"
