# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/constr.xdc

# IP: ip/fifo_generator_6_1/fifo_generator_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_6 || ORIG_REF_NAME==fifo_generator_6} -quiet] -quiet
