# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_4/fifo_generator_4.xci
# IP: The module: 'fifo_generator_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_4/fifo_generator_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_4/fifo_generator_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_4/fifo_generator_4.xci
# IP: The module: 'fifo_generator_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_4/fifo_generator_4.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: e:/Vivado_projects/Crystals-kyber/Crystals-kyber.srcs/sources_1/ip/fifo_generator_4/fifo_generator_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
